import { Card, CardContent } from '@/components/ui/card';
import { MobileButton } from '@/components/mobile';
import { AlertCircle, Info, Mail } from 'lucide-react';
import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Hero */}
      <section className="bg-gradient-to-br from-gray-700 via-gray-800 to-gray-900 text-white px-4 py-12 md:py-16 lg:py-20">
        <div className="container mx-auto">
          <div className="max-w-4xl mx-auto text-center">
            <AlertCircle className="w-12 h-12 md:w-16 md:h-16 mx-auto mb-4 md:mb-6" />
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4 md:mb-6">
              Disclaimer
            </h1>
            <p className="text-base md:text-lg text-gray-300">
              Last Updated: October 22, 2025
            </p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="px-4 py-12 md:py-16 bg-white">
        <div className="container mx-auto">
          <div className="max-w-4xl mx-auto space-y-6 md:space-y-8">
            <Card>
              <CardContent className="p-4 md:p-6">
                <h2 className="text-lg md:text-xl font-bold text-gray-900 mb-3 md:mb-4 flex items-center gap-2">
                  <Info className="w-5 h-5 text-blue-600" /> General Information
                </h2>
                <p className="text-sm md:text-base text-gray-600">
                  The information provided by CR AudioViz AI is for general informational purposes only. All content is provided in good faith, but we make no representation or warranty regarding accuracy, adequacy, or completeness.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4 md:p-6">
                <h2 className="text-lg md:text-xl font-bold text-gray-900 mb-3 md:mb-4">AI-Generated Content</h2>
                <p className="text-sm md:text-base text-gray-600">
                  Content generated by our AI tools may not always be accurate or appropriate. Users are responsible for reviewing and verifying AI-generated content before use.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4 md:p-6">
                <h2 className="text-lg md:text-xl font-bold text-gray-900 mb-3 md:mb-4">External Links</h2>
                <p className="text-sm md:text-base text-gray-600">
                  Our platform may contain links to external websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of third-party sites.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4 md:p-6">
                <h2 className="text-lg md:text-xl font-bold text-gray-900 mb-3 md:mb-4">Limitation of Liability</h2>
                <p className="text-sm md:text-base text-gray-600">
                  CR AudioViz AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Contact */}
      <section className="px-4 py-12 md:py-16 bg-gradient-to-br from-gray-800 to-gray-900 text-white">
        <div className="container mx-auto text-center">
          <Mail className="w-12 h-12 md:w-16 md:h-16 mx-auto mb-4 md:mb-6" />
          <h2 className="text-2xl md:text-3xl font-bold mb-4">Questions?</h2>
          <p className="text-base md:text-lg text-gray-300 mb-6 md:mb-8 max-w-2xl mx-auto">
            Contact our legal team for clarification
          </p>
          <Link href="/contact?subject=Disclaimer" className="inline-block">
            <MobileButton size="lg" className="bg-white text-gray-900 hover:bg-gray-100">
              Contact Legal
            </MobileButton>
          </Link>
        </div>
      </section>
    </div>
  );
}
